/*
   Code generated by Autosar Studio for software Component:
   SeatHeater
*/

#ifndef RTE_HEADER_SeatHeater_h_
#define RTE_HEADER_SeatHeater_h_

#include "SeatHeater_datatypes.h"

/*
   This file contains prototypes for the runnables and data access points
   used by the Software Component (SeatHeater)
*/


#endif
