/*
   Code generated by Autosar Studio for software Component:
   SeatHeater

   This file should contain definitions for the runnables.
   Prototypes for the runnable functions and data access methods

   Example:
   real_T Rte_IRead_swc_Runnable_Step_Port1_DataElement1();

   extern void Runnable_Step(void);

   Refer toSeatHeater_rte.h to find the current supported
   function headers
*/

#include "SeatHeater_rte.h"

/* WRITE YOUR CODE DOWN HERE */

