/*
   Code generated by Autosar Studio for software Component:
   SeatHeater
*/

#ifndef RTE_HEADER_SeatHeater_h_
#define RTE_HEADER_SeatHeater_h_

#include "SeatHeater_datatypes.h"

/*
   This file contains prototypes for the runnables and data access points
   used by the Software Component (SeatHeater)
*/

Boolean Rte_IRead_SeatHeater_SeatHeaterRunnable_Levels_LeftHeatLevel(void);

Boolean Rte_IRead_SeatHeater_SeatHeaterRunnable_Levels_RightHeatLevel(void);

extern void SeatHeaterRunnable(void);

#endif
