/*
   Code generated by Autosar Studio for software Component:
   SeatHeater
*/

#ifndef RTE_HEADER_SeatHeater_h_
#define RTE_HEADER_SeatHeater_h_

#include "SeatHeater_datatypes.h"

/*
   This file contains prototypes for the runnables and data access points
   used by the Software Component (SeatHeater)
*/

UInt32 Rte_IRead_SeatHeater_SeatHeaterRunnable_Levels_LeftHeatLevel(void);

UInt32 Rte_IRead_SeatHeater_SeatHeaterRunnable_Levels_RightHeatLevel(void);

void Rte_IWrite_SeatHeater_SeatHeaterRunnable_LeftSeaterIO_LeftHeaterValue(UInt32 u);

void Rte_IWrite_SeatHeater_SeatHeaterRunnable_RightSeaterIO_RightHeaterValue(UInt32 u);

extern void SeatHeaterRunnable(void);

#endif
