/*
   Code generated by Autosar Studio for software Component:
   HeatRegulator

   This file should contain definitions for the runnables.
   Prototypes for the runnable functions and data access methods

   Example:
   real_T Rte_IRead_swc_Runnable_Step_Port1_DataElement1();

   extern void Runnable_Step(void);

   Refer toHeatRegulator_rte.h to find the current supported
   function headers
*/

#include "HeatRegulator_rte.h"

/* WRITE YOUR CODE DOWN HERE */

void HeatRegulatorRunnable()
{
    UInt32 t = Rte_IRead_HeatRegulator_HeatRegulatorRunnable_RegulatorIO_RegulatorValue();
    Rte_IWrite_HeatRegulator_HeatRegulatorRunnable_RegulatorPosition_Position(t);
    printf("Position: %d", t);
}

