/*
   Code generated by Autosar Studio for software Component:
   SeatSensorRight

   This file should contain definitions for the runnables.
   Prototypes for the runnable functions and data access methods

   Example:
   real_T Rte_IRead_swc_Runnable_Step_Port1_DataElement1();

   extern void Runnable_Step(void);

   Refer toSeatSensorRight_rte.h to find the current supported
   function headers
*/

#include "SeatSensorRight_rte.h"

/* WRITE YOUR CODE DOWN HERE */

void SeatSensorRunnableRight()
{
    Boolean b = Rte_IRead_SeatSensorRight_SeatSensorRunnableRight_SensorRightIO_RightSensorValue();
    Rte_IWrite_SeatSensorRight_SeatSensorRunnableRight_StatusRight_PassengerOnRightSeat(b);
}
