/*
   Code generated by Autosar Studio for software Component:
   SeatSensorRight
*/

#ifndef RTE_HEADER_SeatSensorRight_h_
#define RTE_HEADER_SeatSensorRight_h_

#include "SeatSensorRight_datatypes.h"

/*
   This file contains prototypes for the runnables and data access points
   used by the Software Component (SeatSensorRight)
*/


#endif
