# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-14 17:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_auto_20170514_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directory',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date Created'),
        ),
        migrations.AlterField(
            model_name='file',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date Created'),
        ),
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(blank=True, upload_to=b''),
        ),
        migrations.AlterField(
            model_name='file',
            name='name',
            field=models.CharField(default='File', max_length=100),
        ),
    ]
