# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-14 17:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0003_auto_20170514_1908'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='directory',
            options={'verbose_name_plural': 'Directories'},
        ),
        migrations.RenameField(
            model_name='file',
            old_name='file',
            new_name='saved_file',
        ),
    ]
