/*
   Code generated by Autosar Studio for software Component:
   SeatSensorLeft
*/

#ifndef RTE_HEADER_SeatSensorLeft_h_
#define RTE_HEADER_SeatSensorLeft_h_

#include "SeatSensorLeft_datatypes.h"

/*
   This file contains prototypes for the runnables and data access points
   used by the Software Component (SeatSensorLeft)
*/


#endif
