/*
   Code generated by Autosar Studio for software Component:
   SeatHeatingController

   This file should contain definitions for the runnables.
   Prototypes for the runnable functions and data access methods

   Example:
   real_T Rte_IRead_swc_Runnable_Step_Port1_DataElement1();

   extern void Runnable_Step(void);

   Refer toSeatHeatingController_rte.h to find the current supported
   function headers
*/

#include "SeatHeatingController_rte.h"

/* WRITE YOUR CODE DOWN HERE */

void UpdateHeating()
{
    if (Rte_IRead_SeatHeatingController_UpdateHeating_RightSeatStatus_PassengerOnRightSeat())
    {
        UInt32 t = Rte_IRead_SeatHeatingController_UpdateHeating_RegulatorPosition_Position();
        Rte_IWrite_SeatHeatingController_UpdateHeating_HeaterLevels_RightHeatLevel(t);
    }
    else
        Rte_IWrite_SeatHeatingController_UpdateHeating_HeaterLevels_RightHeatLevel(0);

    if (Rte_IRead_SeatHeatingController_UpdateHeating_LeftSeatStatus_PassengerOnLeftSeat())
    {
        UInt32 t = Rte_IRead_SeatHeatingController_UpdateHeating_RegulatorPosition_Position();
        Rte_IWrite_SeatHeatingController_UpdateHeating_HeaterLevels_LeftHeatLevel(t);
    }
    else
        Rte_IWrite_SeatHeatingController_UpdateHeating_HeaterLevels_LeftHeatLevel(0);
}