/*
   Code generated by Autosar Studio for software Component:
   slid1
*/

#ifndef RTE_HEADER_Data_Type_h_
#define RTE_HEADER_Data_Type_h_

#include "rtetypes.h"

/*
   This file contains defintions for the DataTypes supported
   by the Software Component (slid1)
*/

typedef uint8_T UInt8;

#endif
