/*
   Code generated by Autosar Studio for software Component:
   slid1
*/

#ifndef RTE_HEADER_slid1_h_
#define RTE_HEADER_slid1_h_

#include "slid1_datatypes.h"

/*
   This file contains prototypes for the runnables and data access points
   used by the Software Component (slid1)
*/

void Rte_IWrite_slid1_tsy_p1_gyf(UInt8 u);

extern void tsy(void);

#endif
