/*
   Code generated by Autosar Studio for software Component:
   test
*/

#ifndef RTE_HEADER_test_h_
#define RTE_HEADER_test_h_

#include "datatypes.h"

/*
   This file contains prototypes for the runnables and data access points
   used by the Software Component (test)
*/

void Rte_IWrite_test_dsasa_dsadas_dsa(boolean_Tu);

void Rte_IWrite_test_dsasa_dsadas_dsa(boolean_Tu);

void Rte_IWrite_test_dsasa_dsadas_dsa(boolean_Tu);

void Rte_IWrite_test_mh_dsadas_dsa(boolean_Tu);

void Rte_IWrite_test_mh_dsadas_dsa(boolean_Tu);

void Rte_IWrite_test_mh_dsadas_dsa(boolean_Tu);

extern void dsasa(void);
extern void mh(void);

#endif
