/*
   Code generated by Autosar Studio for software Component:
   Heater
*/

#ifndef RTE_HEADER_Heater_h_
#define RTE_HEADER_Heater_h_

#include "datatypes.h"

/*
   This file contains prototypes for the runnables and data access points
   used by the Software Component (Heater)
*/


#endif
