/*
   Code generated by Autosar Studio for software Component:
   HeatRegulator
*/

#ifndef RTE_HEADER_Data_Type_h_
#define RTE_HEADER_Data_Type_h_

#include "rtetypes.h"

/*
   This file contains defintions for the DataTypes supported
   by the Software Component (HeatRegulator)
*/

typedef boolean_T Boolean;
typedef uint32_T UInt32;

#endif
