/*
   Code generated by Autosar Studio for software Component:
   Regulator
*/

#ifndef RTE_HEADER_Regulator_h_
#define RTE_HEADER_Regulator_h_

#include "datatypes.h"

/*
   This file contains prototypes for the runnables and data access points
   used by the Software Component (Regulator)
*/


#endif
