/*
   Code generated by Autosar Studio for software Component:
   test2
*/

#ifndef RTE_HEADER_test2_h_
#define RTE_HEADER_test2_h_

#include "test2_datatypes.h"

/*
   This file contains prototypes for the runnables and data access points
   used by the Software Component (test2)
*/

extern void new(void);

#endif
