/*
   Code generated by Autosar Studio for software Component:
   DoubleBlink

   This file should contain definitions for the runnables.
   Prototypes for the runnable functions and data access methods

   Example:
   real_T Rte_IRead_swc_Runnable_Step_Port1_DataElement1();

   extern void Runnable_Step(void);

   Refer toDoubleBlink_rte.h to find the current supported
   function headers
*/

#include "DoubleBlinker_rte.h"

/* WRITE YOUR CODE DOWN HERE */

Boolean blink = false;

void TopRunnable()
{
    Boolean toggle = Rte_IRead_DoubleBlinker_TopRunnable_Switch_Toggle();
    if (toggle == false)
    {
        printf("Top Runnable \n");
        blink = !blink;
        Rte_IWrite_DoubleBlinker_TopRunnable_TopLed_TopLed(blink);
    }
}

void BottomRunnable()
{
    Boolean toggle = Rte_IRead_DoubleBlinker_BottomRunnable_Switch_Toggle();
    if (toggle == true)
    {
        printf("Bottom Runnable \n");
        blink = !blink;
        Rte_IWrite_DoubleBlinker_BottomRunnable_BottomLed_BottomLed(blink);
    }
}