# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-14 13:29
from __future__ import unicode_literals

import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Directory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(verbose_name='Date Created')),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(storage=django.core.files.storage.FileSystemStorage(location='/storage'), upload_to=b'')),
                ('file_type', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(verbose_name='Date Created')),
                ('directory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='files.Directory')),
            ],
        ),
    ]
