# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-04 22:48
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Directory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date Created')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='files.Directory')),
            ],
            options={
                'verbose_name_plural': 'Directories',
            },
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_type', models.CharField(max_length=20)),
                ('name', models.CharField(default='File', max_length=100)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date Created')),
                ('directory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='files.Directory')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Autosar', max_length=100)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date Created')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='directory',
            name='project',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='files.Project'),
        ),
        migrations.AlterUniqueTogether(
            name='project',
            unique_together=set([('name', 'user')]),
        ),
        migrations.AlterUniqueTogether(
            name='file',
            unique_together=set([('name', 'file_type', 'directory')]),
        ),
    ]
