# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-14 15:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='name',
            field=models.CharField(default='ph', max_length=100),
        ),
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(blank=True, editable=False, upload_to=b''),
        ),
        migrations.AlterUniqueTogether(
            name='file',
            unique_together=set([('name', 'file_type', 'directory')]),
        ),
    ]
