# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-15 14:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0005_auto_20170615_1453'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={},
        ),
        migrations.RemoveField(
            model_name='project',
            name='directory',
        ),
        migrations.AddField(
            model_name='directory',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='files.Project'),
        ),
    ]
