# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-17 21:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0006_auto_20170615_1643'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='saved_file',
        ),
        migrations.AlterField(
            model_name='directory',
            name='project',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='files.Project'),
        ),
    ]
