# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-18 21:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0007_auto_20170617_2326'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArxmlFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('swc_uid', models.CharField(max_length=20)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='files.File')),
            ],
        ),
    ]
