# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-18 22:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0008_arxmlfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arxmlfile',
            name='swc_uid',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
