# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-24 02:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0010_auto_20170621_1709'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='arxmlfile',
            name='file',
        ),
        migrations.DeleteModel(
            name='ArxmlFile',
        ),
    ]
