/*
   Code generated by Autosar Studio for software Component:
   DoubleBlink
*/

#ifndef RTE_HEADER_DoubleBlink_h_
#define RTE_HEADER_DoubleBlink_h_

#include "DoubleBlink_datatypes.h"

/*
   This file contains prototypes for the runnables and data access points
   used by the Software Component (DoubleBlink)
*/

Boolean Rte_IRead_DoubleBlink_TopRunnable_Switch_Toggle(void);

void Rte_IWrite_DoubleBlink_TopRunnable_TopLed_TopLed(Boolean u);

void Rte_IWrite_DoubleBlink_BottomRunnable_BottomLed_BottomLed(Boolean u);

Boolean Rte_IRead_DoubleBlink_BottomRunnable_Switch_Toggle(void);

extern void TopRunnable(void);
extern void BottomRunnable(void);

#endif
