/*
   Code generated by Autosar Studio for software Component:
   DoubleBlink
*/

#ifndef RTE_HEADER_Data_Type_h_
#define RTE_HEADER_Data_Type_h_

#include "rtetypes.h"

/*
   This file contains defintions for the DataTypes supported
   by the Software Component (DoubleBlink)
*/

typedef boolean_T Boolean;

#endif
