/*
   Code generated by Autosar Studio for software Component:
   Blinker
*/

#ifndef RTE_HEADER_Data_Type_h_
#define RTE_HEADER_Data_Type_h_

#include "rtetypes.h"

/*
   This file contains defintions for the DataTypes supported
   by the Software Component (Blinker)
*/

typedef boolean_T Boolean
typedef real_T Float

#endif
