/*
   Code generated by Autosar Studio for software Component:
   Blinker
*/

#ifndef RTE_HEADER_Blinker_h_
#define RTE_HEADER_Blinker_h_

#include "Blinker_datatypes.h"

/*
   This file contains prototypes for the runnables and data access points
   used by the Software Component (Blinker)
*/

void Rte_IWrite_Blinker_BlinkerRunnable_Led_BlinkElement(Boolean u);

extern void BlinkerRunnable(void);

#endif
