# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-24 02:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('files', '0011_auto_20170624_0454'),
    ]

    operations = [
        migrations.CreateModel(
            name='Composition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(default=b'<function uuid1 at 0x02D912B0>', max_length=20, unique=True)),
                ('file', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='files.File')),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='files.Project')),
            ],
        ),
        migrations.CreateModel(
            name='Connector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(default=b'<function uuid1 at 0x02D912B0>', max_length=20, unique=True)),
                ('composition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arxml.Composition')),
            ],
        ),
        migrations.CreateModel(
            name='DataAccess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='DataAccess', max_length=100, unique=True)),
                ('uid', models.CharField(default=b'<function uuid1 at 0x02D912B0>', max_length=20, unique=True)),
                ('type', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='DataElement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='DataElement', max_length=100, unique=True)),
                ('uid', models.CharField(default=b'<function uuid1 at 0x02D912B0>', max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='DataType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Interface',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Interface', max_length=100, unique=True)),
                ('uid', models.CharField(default=b'<function uuid1 at 0x02D912B0>', max_length=20, unique=True)),
                ('type', models.CharField(default='SENDER-RECEIVER-INTERFACE', max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Port',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Port', max_length=100, unique=True)),
                ('uid', models.CharField(default=b'<function uuid1 at 0x02D912B0>', max_length=20, unique=True)),
                ('type', models.CharField(max_length=40)),
                ('interface', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='arxml.Interface')),
            ],
        ),
        migrations.CreateModel(
            name='Runnable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Runnable', max_length=100, unique=True)),
                ('uid', models.CharField(default=b'<function uuid1 at 0x02D912B0>', max_length=20, unique=True)),
                ('concurrent', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='SoftwareComponent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='SoftwareComponent', max_length=100, unique=True)),
                ('uid', models.CharField(default=b'<function uuid1 at 0x02D912B0>', max_length=20, unique=True)),
                ('implementation_uid', models.CharField(default=b'<function uuid1 at 0x02D912B0>', max_length=20, unique=True)),
                ('behavior_uid', models.CharField(default=b'<function uuid1 at 0x02D912B0>', max_length=20, unique=True)),
                ('package_uid', models.CharField(default=b'<function uuid1 at 0x02D912B0>', max_length=20, unique=True)),
                ('subpackage_uid', models.CharField(default=b'<function uuid1 at 0x02D912B0>', max_length=20, unique=True)),
                ('x', models.IntegerField(default=0)),
                ('y', models.IntegerField(default=0)),
                ('composition', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='arxml.Composition')),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='files.File')),
            ],
        ),
        migrations.CreateModel(
            name='TimingEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='TimingEvent', max_length=100, unique=True)),
                ('uid', models.CharField(default=b'<function uuid1 at 0x02D912B0>', max_length=20, unique=True)),
                ('period', models.FloatField()),
                ('runnable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arxml.Runnable')),
                ('swc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arxml.SoftwareComponent')),
            ],
        ),
        migrations.AddField(
            model_name='runnable',
            name='swc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arxml.SoftwareComponent'),
        ),
        migrations.AddField(
            model_name='port',
            name='swc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arxml.SoftwareComponent'),
        ),
        migrations.AddField(
            model_name='interface',
            name='swc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arxml.SoftwareComponent'),
        ),
        migrations.AddField(
            model_name='datatype',
            name='swc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arxml.SoftwareComponent'),
        ),
        migrations.AddField(
            model_name='dataelement',
            name='interface',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arxml.Interface'),
        ),
        migrations.AddField(
            model_name='dataelement',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arxml.DataType'),
        ),
        migrations.AddField(
            model_name='dataaccess',
            name='data_element',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arxml.DataElement'),
        ),
        migrations.AddField(
            model_name='dataaccess',
            name='port',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arxml.Port'),
        ),
        migrations.AddField(
            model_name='dataaccess',
            name='runnable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arxml.Runnable'),
        ),
        migrations.AddField(
            model_name='connector',
            name='p_port',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='p_port', to='arxml.Port'),
        ),
        migrations.AddField(
            model_name='connector',
            name='r_port',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='r_port', to='arxml.Port'),
        ),
    ]
