# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-04 22:48
from __future__ import unicode_literals

import arxml.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Composition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(default=arxml.models.GetUUID, max_length=100, unique=True)),
                ('file', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='files.File')),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='files.Project')),
            ],
        ),
        migrations.CreateModel(
            name='Connector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(default=arxml.models.GetUUID, max_length=100, unique=True)),
                ('composition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arxml.Composition')),
            ],
        ),
        migrations.CreateModel(
            name='DataAccess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='DataAccess', max_length=100)),
                ('uid', models.CharField(default=arxml.models.GetUUID, max_length=100, unique=True)),
                ('type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='DataElement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='DataElement', max_length=100)),
                ('uid', models.CharField(default=arxml.models.GetUUID, max_length=100, unique=True)),
                ('bool_value', models.BooleanField(default=False)),
                ('float_value', models.FloatField(default=0.0)),
                ('int_value', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='DataElementRef',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timeout', models.FloatField(default=60.0)),
                ('data_element', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arxml.DataElement')),
            ],
        ),
        migrations.CreateModel(
            name='DataType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Interface',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Interface', max_length=100)),
                ('uid', models.CharField(default=arxml.models.GetUUID, max_length=100, unique=True)),
                ('type', models.CharField(default='SENDER-RECEIVER-INTERFACE', max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(default=arxml.models.GetUUID, max_length=100, unique=True)),
                ('subpackage_uid', models.CharField(default=arxml.models.GetUUID, max_length=100, unique=True)),
                ('interfaces_file', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='files.File')),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='files.Project')),
            ],
        ),
        migrations.CreateModel(
            name='Port',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Port', max_length=100)),
                ('uid', models.CharField(default=arxml.models.GetUUID, max_length=100, unique=True)),
                ('type', models.CharField(max_length=40)),
                ('x', models.FloatField(default=0.0)),
                ('y', models.FloatField(default=0.0)),
                ('interface', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='arxml.Interface')),
            ],
        ),
        migrations.CreateModel(
            name='Runnable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Runnable', max_length=100)),
                ('uid', models.CharField(default=arxml.models.GetUUID, max_length=100, unique=True)),
                ('concurrent', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='SoftwareComponent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='SoftwareComponent', max_length=100)),
                ('uid', models.CharField(default=arxml.models.GetUUID, max_length=100, unique=True)),
                ('implementation_uid', models.CharField(default=arxml.models.GetUUID, max_length=100, unique=True)),
                ('behavior_uid', models.CharField(default=arxml.models.GetUUID, max_length=100, unique=True)),
                ('x', models.FloatField(default=0.0)),
                ('y', models.FloatField(default=0.0)),
                ('child_directory', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='files.Directory')),
                ('composition', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='arxml.Composition')),
                ('datatypes_file', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='datatypes_file', to='files.File')),
                ('file', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='swc', to='files.File')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arxml.Package')),
                ('rte_datatypes_file', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='rte_datatypes_file', to='files.File')),
                ('rte_file', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='rte_file', to='files.File')),
                ('runnables_file', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='runnables_file', to='files.File')),
            ],
        ),
        migrations.CreateModel(
            name='TimingEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='TimingEvent', max_length=100)),
                ('uid', models.CharField(default=arxml.models.GetUUID, max_length=100, unique=True)),
                ('period', models.FloatField()),
                ('runnable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arxml.Runnable')),
                ('swc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arxml.SoftwareComponent')),
            ],
        ),
        migrations.AddField(
            model_name='runnable',
            name='swc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arxml.SoftwareComponent'),
        ),
        migrations.AddField(
            model_name='port',
            name='swc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arxml.SoftwareComponent'),
        ),
        migrations.AddField(
            model_name='interface',
            name='package',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='arxml.Package'),
        ),
        migrations.AddField(
            model_name='datatype',
            name='package',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='arxml.Package'),
        ),
        migrations.AddField(
            model_name='dataelementref',
            name='port',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arxml.Port'),
        ),
        migrations.AddField(
            model_name='dataelement',
            name='interface',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arxml.Interface'),
        ),
        migrations.AddField(
            model_name='dataelement',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arxml.DataType'),
        ),
        migrations.AddField(
            model_name='dataaccess',
            name='data_element_ref',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arxml.DataElementRef'),
        ),
        migrations.AddField(
            model_name='dataaccess',
            name='runnable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arxml.Runnable'),
        ),
        migrations.AddField(
            model_name='connector',
            name='p_port',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='p_port', to='arxml.Port'),
        ),
        migrations.AddField(
            model_name='connector',
            name='r_port',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='r_port', to='arxml.Port'),
        ),
        migrations.AlterUniqueTogether(
            name='softwarecomponent',
            unique_together=set([('name', 'composition')]),
        ),
        migrations.AlterUniqueTogether(
            name='interface',
            unique_together=set([('name', 'package')]),
        ),
        migrations.AlterUniqueTogether(
            name='datatype',
            unique_together=set([('type', 'package')]),
        ),
        migrations.AlterUniqueTogether(
            name='dataelementref',
            unique_together=set([('port', 'data_element')]),
        ),
        migrations.AlterUniqueTogether(
            name='connector',
            unique_together=set([('p_port', 'composition'), ('r_port', 'composition')]),
        ),
    ]
