# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-24 12:51
from __future__ import unicode_literals

import arxml.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arxml', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='composition',
            name='uid',
            field=models.CharField(default=arxml.models.GetUUID, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='connector',
            name='uid',
            field=models.CharField(default=arxml.models.GetUUID, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='dataaccess',
            name='uid',
            field=models.CharField(default=arxml.models.GetUUID, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='dataelement',
            name='uid',
            field=models.CharField(default=arxml.models.GetUUID, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='interface',
            name='uid',
            field=models.CharField(default=arxml.models.GetUUID, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='port',
            name='uid',
            field=models.CharField(default=arxml.models.GetUUID, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='runnable',
            name='uid',
            field=models.CharField(default=arxml.models.GetUUID, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='softwarecomponent',
            name='behavior_uid',
            field=models.CharField(default=arxml.models.GetUUID, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='softwarecomponent',
            name='implementation_uid',
            field=models.CharField(default=arxml.models.GetUUID, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='softwarecomponent',
            name='package_uid',
            field=models.CharField(default=arxml.models.GetUUID, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='softwarecomponent',
            name='subpackage_uid',
            field=models.CharField(default=arxml.models.GetUUID, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='softwarecomponent',
            name='uid',
            field=models.CharField(default=arxml.models.GetUUID, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='timingevent',
            name='uid',
            field=models.CharField(default=arxml.models.GetUUID, max_length=20, unique=True),
        ),
    ]
