# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-26 20:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arxml', '0002_auto_20170624_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='softwarecomponent',
            name='x',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='softwarecomponent',
            name='y',
            field=models.FloatField(default=0.0),
        ),
    ]
