# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-27 17:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('arxml', '0003_auto_20170626_2237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='port',
            name='interface',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='arxml.Interface'),
        ),
    ]
