# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-06 22:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arxml', '0003_auto_20170705_0057'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dataelement',
            name='bool_value',
        ),
        migrations.RemoveField(
            model_name='dataelement',
            name='float_value',
        ),
        migrations.RemoveField(
            model_name='dataelement',
            name='int_value',
        ),
    ]
