# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-07 16:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arxml', '0004_auto_20170707_0014'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='proc_id',
            field=models.IntegerField(default=0),
        ),
    ]
