# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-28 15:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arxml', '0005_auto_20170627_2112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='port',
            name='name',
            field=models.CharField(default='Port', max_length=100),
        ),
    ]
