# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-28 16:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arxml', '0006_auto_20170628_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataaccess',
            name='name',
            field=models.CharField(default='DataAccess', max_length=100),
        ),
        migrations.AlterField(
            model_name='dataelement',
            name='name',
            field=models.CharField(default='DataElement', max_length=100),
        ),
        migrations.AlterField(
            model_name='datatype',
            name='type',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='interface',
            name='name',
            field=models.CharField(default='Interface', max_length=100),
        ),
        migrations.AlterField(
            model_name='runnable',
            name='name',
            field=models.CharField(default='Runnable', max_length=100),
        ),
        migrations.AlterField(
            model_name='timingevent',
            name='name',
            field=models.CharField(default='TimingEvent', max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='connector',
            unique_together=set([('p_port', 'composition'), ('r_port', 'composition')]),
        ),
        migrations.AlterUniqueTogether(
            name='datatype',
            unique_together=set([('type', 'swc')]),
        ),
    ]
