# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-15 15:05
from __future__ import unicode_literals

import arxml.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('arxml', '0006_auto_20170708_0611'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationError',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Operation', max_length=100)),
                ('error_code', models.CharField(default='-1', max_length=10)),
                ('uid', models.CharField(default=arxml.models.GetUUID, max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Argument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Arg', max_length=30)),
                ('direction', models.CharField(default='IN', max_length=3)),
                ('uid', models.CharField(default=arxml.models.GetUUID, max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ClientServerInterface',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Operation', max_length=100)),
                ('uid', models.CharField(default=arxml.models.GetUUID, max_length=100, unique=True)),
                ('interface', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arxml.ClientServerInterface')),
            ],
        ),
        migrations.CreateModel(
            name='OperationInvokedEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='OperationInvokedEvent', max_length=100)),
                ('uid', models.CharField(default=arxml.models.GetUUID, max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='OperationRef',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arxml.Operation')),
                ('port', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arxml.Port')),
            ],
        ),
        migrations.CreateModel(
            name='PossibleError',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_error', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arxml.ApplicationError')),
                ('operation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arxml.Operation')),
            ],
        ),
        migrations.CreateModel(
            name='ReadVariableRef',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('runnable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arxml.Runnable')),
            ],
        ),
        migrations.CreateModel(
            name='SenderReceiverInterface',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ServerCallPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='CallPoint', max_length=100, unique=True)),
                ('operation_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arxml.OperationRef')),
                ('runnable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arxml.Runnable')),
            ],
        ),
        migrations.CreateModel(
            name='Variable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Variable', max_length=100)),
                ('comm', models.CharField(default='IMPLICIT', max_length=10)),
                ('uid', models.CharField(default=arxml.models.GetUUID, max_length=100, unique=True)),
                ('swc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arxml.SoftwareComponent')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arxml.DataType')),
            ],
        ),
        migrations.CreateModel(
            name='WriteVariableRef',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('runnable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arxml.Runnable')),
                ('variable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arxml.Variable')),
            ],
        ),
        migrations.AddField(
            model_name='interface',
            name='provider',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='provided_interface', to='arxml.Port'),
        ),
        migrations.AlterField(
            model_name='dataelement',
            name='interface',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arxml.SenderReceiverInterface'),
        ),
        migrations.AddField(
            model_name='senderreceiverinterface',
            name='interface',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='arxml.Interface'),
        ),
        migrations.AddField(
            model_name='readvariableref',
            name='variable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arxml.Variable'),
        ),
        migrations.AddField(
            model_name='operationinvokedevent',
            name='operation_ref',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='arxml.OperationRef'),
        ),
        migrations.AddField(
            model_name='operationinvokedevent',
            name='runnable',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='arxml.Runnable'),
        ),
        migrations.AddField(
            model_name='operationinvokedevent',
            name='swc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arxml.SoftwareComponent'),
        ),
        migrations.AddField(
            model_name='clientserverinterface',
            name='interface',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='arxml.Interface'),
        ),
        migrations.AddField(
            model_name='argument',
            name='operation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arxml.Operation'),
        ),
        migrations.AddField(
            model_name='argument',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arxml.DataType'),
        ),
        migrations.AddField(
            model_name='applicationerror',
            name='interface',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arxml.ClientServerInterface'),
        ),
        migrations.AlterUniqueTogether(
            name='variable',
            unique_together=set([('swc', 'name')]),
        ),
        migrations.AlterUniqueTogether(
            name='possibleerror',
            unique_together=set([('operation', 'application_error')]),
        ),
        migrations.AlterUniqueTogether(
            name='argument',
            unique_together=set([('name', 'type')]),
        ),
    ]
