# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-29 03:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('arxml', '0007_auto_20170628_1810'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataElementRef',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timeout', models.FloatField(default=60.0)),
                ('data_element', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arxml.DataElement')),
                ('port', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arxml.Port')),
            ],
        ),
        migrations.RemoveField(
            model_name='dataaccess',
            name='data_element',
        ),
        migrations.RemoveField(
            model_name='dataaccess',
            name='port',
        ),
        migrations.AddField(
            model_name='dataaccess',
            name='data_element_ref',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='arxml.DataElementRef'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='dataelementref',
            unique_together=set([('port', 'data_element')]),
        ),
    ]
