# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-15 17:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('arxml', '0007_auto_20170915_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interface',
            name='provider',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='provided_interface', to='arxml.Port'),
        ),
    ]
