# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-30 04:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('arxml', '0008_auto_20170915_1933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='port',
            name='interface',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='arxml.Interface'),
        ),
    ]
