# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-29 15:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arxml', '0008_auto_20170629_0524'),
    ]

    operations = [
        migrations.AddField(
            model_name='port',
            name='x',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='port',
            name='y',
            field=models.FloatField(default=0.0),
        ),
    ]
