# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-29 17:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('arxml', '0010_auto_20170629_1905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='softwarecomponent',
            name='child_directory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='files.Directory'),
        ),
    ]
