# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-29 18:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('arxml', '0011_auto_20170629_1958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='softwarecomponent',
            name='datatypes_file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='datatypes_file', to='files.File'),
        ),
        migrations.AlterField(
            model_name='softwarecomponent',
            name='rte_datatypes_file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='rte_datatypes_file', to='files.File'),
        ),
        migrations.AlterField(
            model_name='softwarecomponent',
            name='rte_file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='rte__file', to='files.File'),
        ),
        migrations.AlterField(
            model_name='softwarecomponent',
            name='runnables_file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='runnables_file', to='files.File'),
        ),
    ]
