# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-03 13:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('arxml', '0013_auto_20170629_2034'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataelement',
            name='bool_value',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dataelement',
            name='float_value',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='dataelement',
            name='int_value',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='connector',
            name='p_port',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='p_port', to='arxml.Port'),
        ),
        migrations.AlterField(
            model_name='connector',
            name='r_port',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='r_port', to='arxml.Port'),
        ),
        migrations.AlterField(
            model_name='softwarecomponent',
            name='child_directory',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='files.Directory'),
        ),
        migrations.AlterField(
            model_name='softwarecomponent',
            name='datatypes_file',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='datatypes_file', to='files.File'),
        ),
        migrations.AlterField(
            model_name='softwarecomponent',
            name='file',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='file', to='files.File'),
        ),
        migrations.AlterField(
            model_name='softwarecomponent',
            name='rte_datatypes_file',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='rte_datatypes_file', to='files.File'),
        ),
        migrations.AlterField(
            model_name='softwarecomponent',
            name='rte_file',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='rte_file', to='files.File'),
        ),
        migrations.AlterField(
            model_name='softwarecomponent',
            name='runnables_file',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='runnables_file', to='files.File'),
        ),
    ]
