/*
   Code generated by Autosar Studio for software Component:
   DemoSWC2
*/

#ifndef RTE_HEADER_Data_Type_h_
#define RTE_HEADER_Data_Type_h_

#include "rtetypes.h"

/*
   This file contains defintions for the DataTypes supported
   by the Software Component (DemoSWC2)
*/

typedef boolean_T Boolean;
typedef uint8_T UInt8;

#endif
