/*
   Code generated by Autosar Studio for software Component:
   DemoSWC2
*/

#ifndef RTE_HEADER_DemoSWC2_h_
#define RTE_HEADER_DemoSWC2_h_

#include "DemoSWC2_datatypes.h"

/*
   This file contains prototypes for the runnables and data access points
   used by the Software Component (DemoSWC2)
*/


#endif
