from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver
from rest_framework.authtoken.models import Token
from django.conf import settings
from files.models import File, Project, Directory
from arxml.models import Package, Composition, SoftwareComponent, TimingEvent, Runnable, Port, SenderReceiverInterface, Interface, DataElement, DataAccess, DataElementRef, DataType

@receiver(post_save, sender=settings.AUTH_USER_MODEL)
def create_auth_token(sender, instance=None, created=False, **kwargs):
    if created:
        Token.objects.create(user=instance)

# Create your models here.

def MakeProject(project_name, req_user):
    project = Project(name=project_name, user=req_user)
    project.save()
    directory_name = project_name + str("-") + str(project.id)
    main_directory = Directory(name=directory_name, project=project)
    main_directory.save()
    arxml_file = File(name="Composition", file_type="arxml", directory=main_directory)
    arxml_file.save()
    interfaces_file = File(name="DataTypesAndInterfaces", file_type="arxml", directory=main_directory)
    interfaces_file.save()
    package = Package(project=project, interfaces_file=interfaces_file)
    package.save()
    package.Rewrite()
    composition = Composition(file=arxml_file, project=project)
    composition.save()
    composition.Rewrite()
    return project

def CreateDefaultsForUser(user):
    ### Blink
    project = MakeProject("Blinker", user)
    swc = SoftwareComponent.Make(project, "Blinker", 33.4, 40.57)
    runnable = Runnable(name="BlinkerRunnable", concurrent=True, swc=swc)
    runnable.save()
    event = TimingEvent(name="TimingEvent", runnable=runnable, period=1, swc=swc)
    event.save()
    interface = Interface(name="Blink", package=project.package, type="SENDER-RECEIVER-INTERFACE")
    interface.save()
    blinker_interface = SenderReceiverInterface(interface=interface)
    blinker_interface.save()
    led_port = Port(name="Led", swc=swc, type="P-PORT-PROTOTYPE", interface=interface, x=18.5, y=2.4)
    led_port.save()
    type = DataType(package=project.package, type="Boolean")
    type.save()
    blink_element = DataElement(name="BlinkElement", interface=blinker_interface, type=type)
    blink_element.save()
    ref = DataElementRef(port=led_port, data_element=blink_element)
    ref.save()
    acc = DataAccess(name="BlinkerAccess", runnable=runnable, data_element_ref=ref, type="DATA-WRITE-ACCESS")
    acc.save()
    project.package.Rewrite()
    project.composition.Rewrite()
    swc.runnables_file.Write(open("files/default-projects/Blinker/Blinker/Blinker_runnables.c").read())

    ### Double Blink
    project = MakeProject("DoubleBlinker", user)
    swc = SoftwareComponent.Make(project, "DoubleBlinker", 51.56, 40.2)
    top = Runnable(name="TopRunnable", concurrent=True, swc=swc)
    top.save()
    bottom = Runnable(name="BottomRunnable", concurrent=True, swc=swc)
    bottom.save()
    top_event = TimingEvent(name="TopEvent", runnable=top, period=1, swc=swc)
    top_event.save()
    bottom_event = TimingEvent(name="BottomEvent", runnable=bottom, period=1, swc=swc)
    bottom_event.save()
    input_interface = Interface(name="Input", package=project.package, type="SENDER-RECEIVER-INTERFACE")
    input_interface.save()
    input_sr_interface = SenderReceiverInterface(interface=input_interface)
    input_sr_interface.save()
    bottom_interface = Interface(name="Bottom", package=project.package, type="SENDER-RECEIVER-INTERFACE")
    bottom_interface.save()
    bottom_sr_interface = SenderReceiverInterface(interface=bottom_interface)
    bottom_sr_interface.save()
    top_interface = Interface(name="Top", package=project.package, type="SENDER-RECEIVER-INTERFACE")
    top_interface.save()
    top_sr_interface = SenderReceiverInterface(interface=top_interface)
    top_sr_interface.save()
    switch_port = Port(name="Switch", swc=swc, type="R-PORT-PROTOTYPE", interface=input_sr_interface, x=-1.5, y=2.08)
    switch_port.save()
    top_led_port = Port(name="TopLed", swc=swc, type="P-PORT-PROTOTYPE", interface=top_sr_interface, x=18.5, y=2.4)
    top_led_port.save()
    bottom_led_port = Port(name="BottomLed", swc=swc, type="P-PORT-PROTOTYPE", interface=bottom_sr_interface, x=18.5, y=7.8)
    bottom_led_port.save()
    type = DataType(package=project.package, type="Boolean")
    type.save()
    toggle = DataElement(name="Toggle", interface=input_sr_interface, type=type)
    toggle.save()
    top_de = DataElement(name="TopLed", interface=top_sr_interface, type=type)
    top_de.save()
    bottom_de = DataElement(name="BottomLed", interface=bottom_sr_interface, type=type)
    bottom_de.save()
    ref1 = DataElementRef(port=switch_port, data_element=toggle)
    ref1.save()
    ref2 = DataElementRef(port=top_led_port, data_element=top_de)
    ref2.save()
    ref3 = DataElementRef(port=bottom_led_port, data_element=bottom_de)
    ref3.save()
    acc1 = DataAccess(name="TopInputAccess", runnable=top, data_element_ref=ref1, type="DATA-READ-ACCESS")
    acc1.save()
    acc2 = DataAccess(name="BottomInputAccess2", runnable=bottom, data_element_ref=ref1, type="DATA-READ-ACCESS")
    acc2.save()
    acc3 = DataAccess(name="TopOutputAccess", runnable=top, data_element_ref=ref2, type="DATA-WRITE-ACCESS")
    acc3.save()
    acc4 = DataAccess(name="BottomOutputAccess", runnable=bottom, data_element_ref=ref3, type="DATA-WRITE-ACCESS")
    acc4.save()
    project.package.Rewrite()
    project.composition.Rewrite()
    swc.runnables_file.Write(open("files/default-projects/DoubleBlinker/DoubleBlinker/DoubleBlinker_runnables.c").read())
