/*
   Code generated by Autosar Studio for software Component:
   DemoSWC
*/

#ifndef RTE_HEADER_DemoSWC_h_
#define RTE_HEADER_DemoSWC_h_

#include "DemoSWC_datatypes.h"

/*
   This file contains prototypes for the runnables and data access points
   used by the Software Component (DemoSWC)
*/


#endif
